### PR TITLE
Allow targeting only declarations with !important set in object mode

### PR DESCRIPTION
**Pull request by sujeetpillai**
This change allows you to target declarations where !important is set.

### CODE REVIEW

**Comment by pratikpatel-aurochs** [comment]
@andrewvasilchuk Any update on this?

**Comment by akashmelkeri-incentius** [comment]
@andrewvasilchuk Any update on this?

**Comment by andrewvasilchuk** [comment]
@pratikpatel-aurochs, @akashmelkeri-incentius I _promise_ to release a patch today or tomorrow. It's a surprise for me that this library is still used by someone.

**Comment by pratikpatel-aurochs** [comment]
> @pratikpatel-aurochs, @akashmelkeri-incentius I _promise_ to release a patch today or tomorrow. It's a surprise for me that this library is still used by someone.

Awesome

**Comment by andrewvasilchuk** [comment]
Published v1.1.0

**Pull request merged**
